repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    #rev: "v0.11.11"
    rev: "v0.9.4"
    hooks:
      - id: ruff
#      - id: ruff-format
#        args: [--fix, --show-fixes, --exit-non-zero-on-fix]
